------------------------------------------------------------
-- TABELA: TB_EQUIPE
------------------------------------------------------------
CREATE TABLE TB_EQUIPE (
  ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOME  VARCHAR2(100) NOT NULL,
  SETOR VARCHAR2(100)
);

------------------------------------------------------------
-- TABELA: TB_USUARIO
------------------------------------------------------------
CREATE TABLE TB_USUARIO (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOME        VARCHAR2(100) NOT NULL,
  EMAIL       VARCHAR2(150) NOT NULL,
  SENHA_HASH  VARCHAR2(255) NOT NULL,
  ROLE        VARCHAR2(30)  NOT NULL,
  EQUIPE_ID   NUMBER,
  CRIADO_EM   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  ATUALIZADO_EM TIMESTAMP
);
CREATE UNIQUE INDEX UQ_TB_USUARIO_EMAIL ON TB_USUARIO(EMAIL);
CREATE INDEX IX_TB_USUARIO_EQUIPE ON TB_USUARIO(EQUIPE_ID);

------------------------------------------------------------
-- TABELA: TB_CHECKIN  (check-in de bem-estar)
------------------------------------------------------------
CREATE TABLE TB_CHECKIN (
  ID               NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USUARIO_ID       NUMBER        NOT NULL,
  DATA_HORA        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  HUMOR            NUMBER(1)     NOT NULL CHECK (HUMOR BETWEEN 1 AND 5),
  NIVEL_ESTRESSE   NUMBER(2)     NOT NULL CHECK (NIVEL_ESTRESSE BETWEEN 1 AND 10),
  QUALIDADE_SONO   NUMBER(2)     NOT NULL CHECK (QUALIDADE_SONO BETWEEN 1 AND 10),
  SINTOMAS_FISICOS VARCHAR2(255),
  OBSERVACOES      VARCHAR2(500)
);
CREATE INDEX IX_TB_CHECKIN_USUARIO ON TB_CHECKIN(USUARIO_ID);
CREATE INDEX IX_TB_CHECKIN_DATA ON TB_CHECKIN(DATA_HORA);

------------------------------------------------------------
-- TABELA: TB_ESTACAO_TRABALHO (estações monitoradas pelo IoT)
------------------------------------------------------------
CREATE TABLE TB_ESTACAO_TRABALHO (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOME        VARCHAR2(100) NOT NULL,
  LOCALIZACAO VARCHAR2(200)
);

------------------------------------------------------------
-- TABELA: TB_LEITURA_AMBIENTE (leituras dos sensores)
------------------------------------------------------------
CREATE TABLE TB_LEITURA_AMBIENTE (
  ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ESTACAO_ID   NUMBER      NOT NULL,
  TEMPERATURA  NUMBER(4,1),
  RUIDO        NUMBER(4,1),
  LUMINOSIDADE NUMBER(6,2),
  DATA_LEITURA TIMESTAMP   DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX IX_TB_LEITURA_ESTACAO ON TB_LEITURA_AMBIENTE(ESTACAO_ID);
CREATE INDEX IX_TB_LEITURA_DATA ON TB_LEITURA_AMBIENTE(DATA_LEITURA);

------------------------------------------------------------
-- TABELA: TB_PLANO_ACAO (planos de ação do RH / gestão)
------------------------------------------------------------
CREATE TABLE TB_PLANO_ACAO (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EQUIPE_ID   NUMBER      NOT NULL,
  DESCRICAO   VARCHAR2(255) NOT NULL,
  DATA_INICIO DATE,
  DATA_FIM    DATE,
  STATUS      VARCHAR2(20) NOT NULL
    CHECK (STATUS IN ('PLANEJADO','EM_ANDAMENTO','CONCLUIDO'))
);
CREATE INDEX IX_TB_PLANO_EQUIPE ON TB_PLANO_ACAO(EQUIPE_ID);

------------------------------------------------------------
-- RELACIONAMENTOS (FKs)
------------------------------------------------------------
ALTER TABLE TB_USUARIO
  ADD CONSTRAINT FK_USUARIO_EQUIPE
  FOREIGN KEY (EQUIPE_ID) REFERENCES TB_EQUIPE(ID);

ALTER TABLE TB_CHECKIN
  ADD CONSTRAINT FK_CHECKIN_USUARIO
  FOREIGN KEY (USUARIO_ID) REFERENCES TB_USUARIO(ID);

ALTER TABLE TB_LEITURA_AMBIENTE
  ADD CONSTRAINT FK_LEITURA_ESTACAO
  FOREIGN KEY (ESTACAO_ID) REFERENCES TB_ESTACAO_TRABALHO(ID);

ALTER TABLE TB_PLANO_ACAO
  ADD CONSTRAINT FK_PLANO_EQUIPE
  FOREIGN KEY (EQUIPE_ID) REFERENCES TB_EQUIPE(ID);
