--DROP TABLE TB_CHECKIN CASCADE CONSTRAINTS PURGE;
--DROP TABLE TB_EQUIPE CASCADE CONSTRAINTS PURGE;
--DROP TABLE TB_USUARIO CASCADE CONSTRAINTS PURGE;
--DROP TABLE TB_ESTACAO_TRABALHO CASCADE CONSTRAINTS PURGE;
--DROP TABLE TB_LEITURA_AMBIENTE CASCADE CONSTRAINTS PURGE;
--DROP TABLE TB_PLANO_ACAO CASCADE CONSTRAINTS PURGE;

-- 1) Mostrar usuários
SELECT ID, NOME, EMAIL, EQUIPE_ID 
FROM TB_USUARIO 
ORDER BY ID;

-- 2) Mostrar check-ins antes e depois do POST
SELECT ID, USUARIO_ID, DATA_HORA, HUMOR, NIVEL_ESTRESSE, QUALIDADE_SONO, SINTOMAS_FISICOS, OBSERVACOES
FROM TB_CHECKIN
ORDER BY ID DESC;

-- 3) Conferir humor médio (mostra dados consultados pela função)
SELECT USUARIO_ID, HUMOR 
FROM TB_CHECKIN
WHERE TRUNC(DATA_HORA) BETWEEN DATE '2025-01-01' AND DATE '2025-12-31';

-- 4) Conferir estresse e dados usados para cálculo do índice de risco
SELECT USUARIO_ID, HUMOR, NIVEL_ESTRESSE, QUALIDADE_SONO
FROM TB_CHECKIN
ORDER BY DATA_HORA DESC;

